In [1]:
import pandas as pd
df= pd.read_csv('/kaggle/input/updated-dataset/updated_nutrition_data.csv')

In [2]:
df=df.head(30000)

In [3]:
df

,id,calories,caloriesFromFat,totalFat,saturatedFat,cholesterol,sodium,potassium,totalCarbohydrates,dietaryFiber,...,magnesium,folate,breakfast0,lunch0,dinner0,weight_in_kg,height_in_cm,player_value,Blood_Type,injury_type
0,150001,2455.0,1156.0,128.5,50.4,694.0,4477.0,3377.0,239.8,17.6,...,356.0,1.184,16871,40536,24597,71.78,159.19,4,3,5
1,150002,3515.0,1291.0,143.5,49.1,524.0,7766.0,3734.0,408.1,37.2,...,624.0,1.772,8154,5039,21650,66.60,163.59,1,1,5
2,150003,3518.0,1709.0,190.0,63.3,1079.0,5261.0,2670.0,354.1,21.6,...,400.0,1.112,39080,4054,6145,58.70,178.21,6,2,2
3,150004,3771.0,1207.0,134.0,44.3,294.0,3515.0,4667.0,560.8,44.3,...,676.0,1.264,4701,3282,16377,73.84,159.37,9,2,3
4,150005,3439.0,1191.0,132.2,32.7,751.0,3617.0,6585.0,399.0,35.3,...,536.0,1.324,1125,7973,13505,68.93,165.90,7,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,179996,4146.0,2254.0,250.5,91.6,1006.0,4978.0,4601.0,280.2,21.7,...,664.0,0.896,26033,4662,5967,53.55,166.64,8,1,4
29996,179997,2587.0,972.0,107.9,39.6,471.0,3835.0,3324.0,315.3,26.6,...,508.0,1.196,1525,8942,6816,63.64,159.67,5,6,2
29997,179998,3052.0,1389.0,154.3,52.0,470.0,2933.0,2934.0,317.7,23.8,...,676.0,2.196,19375,6726,615,71.30,178.75,9,3,5
29998,179999,3268.0,1592.0,176.9,73.5,886.0,4186.0,3146.0,254.1,15.8,...,464.0,0.624,25948,4130,14509,65.79,168.41,7,2,5
29999,180000,2839.0,912.0,101.3,29.1,452.0,2144.0,3269.0,302.8,24.0,...,640.0,0.968,3471,7291,3224,59.92,176.63,7,7,6

In [4]:
from sklearn.model_selection import train_test_split
# Define your input and output columns
input_columns = ['player_value','weight_in_kg', 'height_in_cm','Blood_Type','injury_type']#'weight_in_kg', 'height_in_cm',
output_columns = ['calories','totalFat','totalCarbohydrates','dietaryFiber','protein','vitaminC']

# Split your data into input (X) and output (y)
X = df[input_columns]
y = df[output_columns]

# Split your data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
X

       player_value  weight_in_kg  height_in_cm  Blood_Type  injury_type
0                 4         71.78        159.19           3            5
1                 1         66.60        163.59           1            5
2                 6         58.70        178.21           2            2
3                 9         73.84        159.37           2            3
4                 7         68.93        165.90           2            1
...             ...           ...           ...         ...          ...
29995             8         53.55        166.64           1            4
29996             5         63.64        159.67           6            2
29997             9         71.30        178.75           3            5
29998             7         65.79        168.41           2            5
29999             7         59.92        176.63           7            6

[30000 rows x 5 columns]

In [6]:
y

       calories  totalFat  totalCarbohydrates  dietaryFiber  protein  vitaminC
0        2455.0     128.5               239.8          17.6     91.7     229.8
1        3515.0     143.5               408.1          37.2    157.7     175.2
2        3518.0     190.0               354.1          21.6    108.3     143.4
3        3771.0     134.0               560.8          44.3     88.9     232.8
4        3439.0     132.2               399.0          35.3    143.1     312.6
...         ...       ...                 ...           ...      ...       ...
29995    4146.0     250.5               280.2          21.7    193.9     223.2
29996    2587.0     107.9               315.3          26.6     99.8      56.4
29997    3052.0     154.3               317.7          23.8    109.8     130.2
29998    3268.0     176.9               254.1          15.8    136.5      66.6
29999    2839.0     101.3               302.8          24.0    149.5      63.0

[30000 rows x 6 columns]

In [7]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor


# Define base regressor
base_regressor = RandomForestRegressor(random_state=42)

# Wrap base regressor with MultiOutputRegressor
model = MultiOutputRegressor(base_regressor)

In [8]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'estimator__n_estimators': [50, 10, 150],
    'estimator__max_depth': [None, 15, 20, 25],
    'estimator__min_samples_split': [2, 5, 10],
    'estimator__min_samples_leaf': [1, 2, 4],
    'estimator__bootstrap': [True, False]
}

# Instantiate the grid search model
grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=-1, verbose=1)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

print("Best parameters found: ", best_params)
print("Best score found: ", grid_search.best_score_)

# Use the best model to make predictions
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

Fitting 3 folds for each of 216 candidates, totalling 648 fits

/opt/conda/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Best parameters found:  {'estimator__bootstrap': True, 'estimator__max_depth': 15, 'estimator__min_samples_leaf': 1, 'estimator__min_samples_split': 10, 'estimator__n_estimators': 150}
Best score found:  -0.013973785979129376

In [9]:
from sklearn import metrics

# Calculate Mean Absolute Error
mae = metrics.mean_absolute_error(y_test, y_pred)

# Calculate Mean Squared Error
mse = metrics.mean_squared_error(y_test, y_pred)

# Calculate R-squared
r2 = metrics.r2_score(y_test, y_pred)

print(f'Mean Absolute Error (MAE): {mae}')
print(f'Mean Squared Error (MSE): {mse}')
print(f'R-squared (R²): {r2}')

# Mean Absolute Error (MAE): 5143771287242.546
# Mean Squared Error (MSE): 3.016225978329049e+25
# R-squared (R²): -1.3561142207985422e+25

Mean Absolute Error (MAE): 108.24961473503829
Mean Squared Error (MSE): 61730.91756677642
R-squared (R²): -0.007372954750805831

In [10]:
from joblib import dump

# Save the model to disk
filename = '6 features_updated.joblib'
dump(best_model, filename)

['6 features_updated.joblib']